version: "1.25"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on :
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
      - "4343:443"
    networks:
      - wordpress_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: www-data
      WORDPRESS_DB_PASSWORD: EscravoDa42
      WORDPRESS_DB_HOST: mariadb
    networks:
      - wordpress_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: www-data
      MYSQL_PASSWORD: EscravoDa42
      MYSQL_ROOT_PASSWORD: JuninMatadorDePorco
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
