version: "1.25"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on :
      - wordpress
    ports:
      - "8080:80"
      - "4343:443"
    networks:
      - wordpress_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: mariadb
    networks:
      - wordpress_network

  # mariadb:
  #   build:
  #     context: ./requirements/mariadb
  #     dockerfile: Dockerfile
  #   container_name: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: wordpress_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: root_password
  #   networks:
  #     - wordpress_network

networks:
  wordpress_network:
    driver: bridge
