version: "2.16"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on :
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-files:/var/www/html
    networks:
      - wordpress_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress-files:/var/www/html
      - wordpress-db:/var/lib/mysql
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    networks:
      - wordpress_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - wordpress-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress-files:
  wordpress-db:
